### ISSUE TITLE
Names clash between variant-lite and expected-lite

### ISSUE THREAD

**Issue by flexferrum** [martinmoene/variant-lite#16]
I included both nonstd/expected.hpp and nonstd/variant.hpp in one file and got the following error:

```
/projects/flexferrum-Jinja2Cpp/thirdparty/nonstd/expected-light/include/nonstd/expected.hpp:531:8: error: redefinition of ‘struct nonstd::in_place_t’
 struct in_place_t{};
        ^
/projects/flexferrum-Jinja2Cpp/thirdparty/nonstd/variant-light/include/nonstd/variant.hpp:272:8: error: previous definition of ‘struct nonstd::in_place_t’
 struct in_place_t {};
        ^
```

**Comment by flexferrum** [comment]
I'm considering the following way: move common types, macros etc. to separate repo and then combine the 'production' headers via Jinja2 - just include one Jinja2 template into another. It allows to keep the common code consistent.

**Comment by martinmoene** [comment]
This is a 'duplicate' of [issue 14 at expected-lite ](https://github.com/martinmoene/expected-lite/issues/14).

I'd like to keep the shared "`in_place` infrastructure" as simple as it is now and refrain from file generation for *any-lite*, *optional-lite* and *expected-lite*.

I've had a go at using *optional-lite*'s (etc.) `in_place` setup before, but was not immediately succesful (can't remember why). Also I can't remember from the top of my head why *expected-lite*'s `in_place` is as it is. Further, I have a [longstanding action to update *expected-lite* (old repo)](https://github.com/martinmoene/expected-dark/issues/20) ([new repo](https://github.com/martinmoene/expected-lite/issues/3))  to the [latest proposal](http://wg21.link/p0323), a moving target.

References:
- *variant-lite* issue #1 
- *expected-lite* [issue 14: can't work with optional-lite because of nonstd::in_place_t ](https://github.com/martinmoene/expected-lite/issues/14)
- *expected-lite*, [issue 3: Update to latest proposal](https://github.com/martinmoene/expected-lite/issues/3)
- *expected-lite*, [issue 20: Update to latest proposal](https://github.com/martinmoene/expected-dark/issues/20) (old repo)
- [P0323rx std::expected](http://wg21.link/p0323)

**Comment by martinmoene** [comment]
Done per [nonstd-lite issue 17](https://github.com/martinmoene/nonstd-lite/issues/17).

**Comment by flexferrum** [comment]
I'll try to check it out tonight. Thanks!

**Comment by flexferrum** [comment]
It works!

**Comment by martinmoene** [comment]
Nice! Thanks for letting me know.
